site_name: Fosscord Docs
repo_url: https://github.com/Stylix58/fosscord-docs
plugins:
  - section-index
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  font: Open Sans
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - navigation.expand
