name: Github Pages Publish

on:
    push:
        branches:
            - master
    workflow_dispatch:
        branches:
            - master
            
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                python-version: 3.x
            - run: pip install mkdocs-material mkdocs-section-index
            - uses: Stylix58/gh-pages-deploy-action@master
              with:
                  access-token: ${{ secrets.ACCESS_TOKEN }}
                  custom-domain: docs.fosscord.com
                  source-directory: site
                  build-command: mkdocs build
